### ISSUE TITLE
wbar and hlrpad undeclared

### ISSUE THREAD

**Issue by jodojodo** [ashish-yadav11/dwmblocks#1]
Hello,
I use Dwm with some other patches and tried your patch for dwmblocks, 
but I cannot build dwm, because of undelcared variables wbar and hlrpad. 

Can you tell me where those are defined? 
![Bildschirmfoto zu 2020-07-18 00-43-20](https://user-images.githubusercontent.com/7256369/87836321-f389e300-c88f-11ea-8337-9df2cbe542dc.png)

**Comment by ashish-yadav11** [comment]
Ohh, My bad.
Will fix in a minute.

**Comment by ashish-yadav11** [comment]
Can you build your dwm now?

**Comment by jodojodo** [comment]
Hey, yes it builds now. Tanks :)
