### ISSUE TITLE
A block is not clickable if it's signal is 0

### ISSUE THREAD

**Issue by mastopgunaf** [ashish-yadav11/dwmblocks#10]
A comment in blocks.h says:
```
 * Set signal to 0 if signalling is not required for the block.
```
However, if I have a block that doesn't require signaling, but is clickable and updated through an interval, it requires a unique signal number, otherwise it becomes non-clickable.

For example, this block wouldn't be clickable:
```
{ PATH("cpu.sh"),               PATH("cpu_click.sh"),                   1,              0 }
```

But this block will be:
```
{ PATH("cpu.sh"),               PATH("cpu_click.sh"),                   1,              2 }
```

**Comment by ashish-yadav11** [comment]
The way clickabity works is dwm signals dwmblocks to update the block on clicks by using its signal number (which is written in a char before the block output). If you don't keep a signal value for the block how can dwm signal dwmblocks to update a block.
I am going to state the comment more clearly but nothing more can be done.

**Comment by mastopgunaf** [comment]
> The way clickabity works is dwm signals dwmblocks to update the block on clicks by using its signal number (which is written in a char before the block output). If you don't keep a signal value for the block how can dwm signal dwmblocks to update a block.
> I am going to state the comment more clearly but nothing more can be done.

Oh, that's what I was thinking. Well, thanks regardless!

**Comment by ashish-yadav11** [comment]
My bad, I rushed through your message.
