### ISSUE TITLE
Colored output doesn't work in Void Linux

### ISSUE THREAD

**Issue by mastopgunaf** [ashish-yadav11/dwmblocks#13]
I recently decided to move from Arch to Void Linux, and one thing I immediately noticed is that colored output in dwmblocks stopped working, even though I'm using the same exact dwm build I used back on Arch. As said in the readme, I make my script output raw characters starting from \x0b, and of course I applied a patch for dwm (without systray). Clickability works fine. Maybe I missed something and that's not Void's fault?

As an example, my date script:
`printf "    $(date +'%a')\x0c,\x0b $(date +'%b %-d')      $(date +'%-H')\x0c:\x0b$(date +'%M')\0"`

Result:
https://i.imgur.com/EMaXATx.png

**Comment by ashish-yadav11** [comment]
Maybe you are using /bin/sh as the shebang and the default shell is different in void and its builtin printf doesn't parse \x0c as raw character. Try putting `printf "  $(date +'%a'), $(date +'%b %-d')  $(date +'%-H'):$(date +'%M')\0"` in your date script.

**Comment by mastopgunaf** [comment]
Indeed, I had #!/bin/sh at the top of my script. I changed it to #!/bin/bash and everything works fine now. I'll probably still figure out how to escape them in POSIX shell, as I don't like using bash in my scripts.

**Comment by ashish-yadav11** [comment]
If you use vim, you can manually type the raw characters in the argument to printf by using `Ctrl-v` followed by `x` followed by the two digit hexadecimal number (eg. `0c`). Otherwise you can use octal numbers in posix shell with `printf \14` for printing '\x0c' for example.
