### ISSUE TITLE
How to add more than 10 blocks ?

### ISSUE THREAD

**Issue by romariorobby** [ashish-yadav11/dwmblocks#15]
Is it possible to add more than 10 blocks ?

**Comment by ashish-yadav11** [comment]
You can have more than 9 blocks but you can only keep 9 clickable at max.

**Comment by romariorobby** [comment]
Sorry, I mean.. adding more clickable things. so theres no way to adding more than 9?

**Comment by ashish-yadav11** [comment]
With the current setup no. You will have to tweak the dwm patch. I will see if I can do something about it.

**Comment by romariorobby** [comment]
Right. Thanks.

**Comment by ashish-yadav11** [comment]
Checkout the latest commit. I have added the ability to increase the limit.

**Comment by romariorobby** [comment]
Oh sure.I'll check that later. Thanks I appreciate that.

**Comment by romariorobby** [comment]
i've tried the new commit .it seems when I adding more than 15 blocks, it gets combine smaler . 
![pic-selected-201229-2237-46](https://user-images.githubusercontent.com/40323094/103295960-a78abf00-4a27-11eb-8484-d33f7dda7ee6.png)

**Comment by ashish-yadav11** [comment]
So delimiter is getting skipped. What delimiter are you using by the way.

**Comment by ashish-yadav11** [comment]
And does it work before 15 blocks (for example for 14 blocks)?

**Comment by romariorobby** [comment]
Just one empty spaces . its perfectly fine when  DELIMITERCHAR sets to 14.

**Comment by ashish-yadav11** [comment]
Okay weird, let me see.

**Comment by ashish-yadav11** [comment]
Send the output of `xgetrootname`. (Redirect it to a file and then copy paste here).

**Comment by romariorobby** [comment]
📦98	 📰1788
 📬2 🔊99% 🖥: 14G/59G ♻️99% 🕚 Tuesday 29/12/20 11:47PM 🔻   0B 🔺 164B 📶 100% ❎ ❓

**Comment by ashish-yadav11** [comment]
I can't access the raw characters in your message. Can you mail me the output at `ashishkumar.yadav@students.iiserpune.ac.in`?

**Comment by ashish-yadav11** [comment]
I got the mail from github, Nevermind.

**Comment by romariorobby** [comment]
I've sent you mail already. anyway, did it work on your machines with 15 blocks clickable item?

**Comment by ashish-yadav11** [comment]
I am in the middle of something else. I will report you in an hour.

**Comment by ashish-yadav11** [comment]
It is working for me. I set DELIMITERENDCHAR to 16 and set your output as root name. Space is shown between the blocks for me.

**Comment by ashish-yadav11** [comment]
Okay, I realized I should have set it to 15. But it works in that case too.

**Comment by ashish-yadav11** [comment]
![2020-12-29-234151_757x21](https://user-images.githubusercontent.com/60382031/103304819-9ba2fb00-4a2f-11eb-8729-cbf358fcaed5.png)

**Comment by ashish-yadav11** [comment]
I have set A as the delimiter.

**Comment by ashish-yadav11** [comment]
How many colors do you have in you colors array in config.h?

**Comment by romariorobby** [comment]
10 colors, so i might not patch dwm correctly. i tried with vanilla dwm with only systray patch, it works fine.

**Comment by ashish-yadav11** [comment]
Replace the line
```
if ((unsigned char)*ts > LENGTH(colors) + DELIMITERENDCHAR) {
```
with
```
if ((unsigned char)*ts >= ' ' || (unsigned char)*ts > LENGTH(colors) + DELIMITERENDCHAR) {
```
in drawbar function in dwm.c with your current setup and see if the issue continues to occur.

**Comment by romariorobby** [comment]
Well, Problem solved. Thanks.

**Comment by ashish-yadav11** [comment]
I have updated the patches with the fix and a couple of other small improvements in the latest commit. Thanks for reporting the issue.
