### ISSUE TITLE
dwmblocks (dwm patch does not compile)

### ISSUE THREAD

**Issue by udav404** [ashish-yadav11/dwmblocks#16]
Hi,
This is the first time I open an isues, I hope it done correctly.

I have challenges with the patches that must make all the functionalites accessible.
Both patches show the same error message when I compile dwm. I tried both versions of the patch according to the instructions on the github page.

This one **dwm-systray-dwmblocks-6.2.diff** I added on top of the systray patch.

This one **dwm-systray-dwmblocks-6.2.diff** i added without systray patch

This is the error message:

`dwm.c: In function ‘motionnotify’:
dwm.c:1215:25: error: too few arguments to function ‘unfocus’
 1215 |                         unfocus(selmon->sel, 1);
      |                         ^~~~~~~
dwm.c:232:13: note: declared here
  232 | static void unfocus(Client *c, int setfocus, Client *nextfocus);
      |             ^~~~~~~
dwm.c:1210:10: warning: unused variable ‘sel’ [-Wunused-variable]
 1210 |  Client *sel;
      |          ^~~
make: *** [Makefile:18: dwm.o] Error 1`

Any ideas on how this can be solved?

**Comment by ashish-yadav11** [comment]
I can't reproduce the issue with vanilla dwm 6.2. You must have used some conflicting patch. I would suggest patching vanilla dwm with systray (if you use it) patch, then using dwmblocks patch then finally using other patches. You will have to resolve conflicts yourself. Morever, I don't see any patch on suckless's site which change unfocus' definition to what your error suggests.

**Comment by udav404** [comment]
Ok, it was worth a try.
unfocus' definition is in the sources code. dwmblocks patch change som off lines in between `@@ -1122,14 +1165,24 @@
` 
I'm pretty sure you're doing something different than me. None of the patches go through clean. Both issue reject files, with many lines compared to the other suckless patches.

But thanks, anyway. I'm trying to find another solution on the status bar.

**Comment by ashish-yadav11** [comment]
unfocus' definition is indeed in the source code of dwm but it only has two arguments. Your error message suggests that what you are building has one extra argument Client *nextfocus. That's what I was talking about. Anyway good luck.
