### ISSUE TITLE
Error while executing dwmblocks 

### ISSUE THREAD

**Issue by burton11** [ashish-yadav11/dwmblocks#17]
After compiling dwmblocks and trying to to run it , I get the following error:
getcmd - child - execv : No such file or directory.

I don't seem to find what the issue is here exactly.

**Comment by ashish-yadav11** [comment]
Have you changed the PATH variable at the top of your `config.h`. It should point to the folder where your scripts are saved.

**Comment by burton11** [comment]
doesn't seem to work, how do you define it correctly?

**Comment by ashish-yadav11** [comment]
Send the line that you have in your blocks.h

**Comment by burton11** [comment]
I basically just substituted your path with mine:
#define PATH(name)                      "/home/burton/dwmblocks/blocks/"name
after this i try to run dwmblocks in the terminal and the error still persists.
i just cloned the repo and build it, didn't move the file anywhere.

**Comment by ashish-yadav11** [comment]
have you build it again after changing the file? Are you sure `/home/burton/dwmblocks/blocks/` points to the folder where the scripts are located? Run `ls /home/burton/dwmblocks/blocks/`.

**Comment by burton11** [comment]
You were right i forgot to run make after I made the changes , thank you very very much !
