### ISSUE TITLE
What if a block has multiple printf functions

### ISSUE THREAD

**Issue by Infinemen** [ashish-yadav11/dwmblocks#19]
Hi, again

Thanks to your advice, I had a satisfactory result yesterday. Now there's a new problem, if I want to print multiple times in a block, how do I do it? At this point, it looks like the block will only execute the first gprintf function.

By the way, the shell script I want to use looks like this：

```
cache=/tmp/cpubarscache

# id total idle
stats=$(awk '/cpu[0-9]+/ {printf "%d %d %d\n", substr($1,4), ($2 + $3 + $4 + $5), $5 }' /proc/stat)
[ ! -f $cache ] && echo "$stats" > "$cache"
old=$(cat "$cache")
#printf "ﳇ "
echo "$stats" |
	while read -r row; do
	  id=${row%% *}
	  rest=${row#* }
	  total=${rest%% *}
	  idle=${rest##* }

	case "$(echo "$old" | awk '{if ($1 == id)
		printf "%d\n", (1 - (idle - $3)  / (total - $2))*100 /12.5}' \
		id="$id" total="$total" idle="$idle")" in

		"0") printf "▁";;
		"1") printf "▂";;
		"2") printf "▃";;
		"3") printf "▄";;
		"4") printf "▅";;
		"5") printf "▆";;
		"6") printf "▇";;
		"7") printf "█";;
		"8") printf "█";;
	esac
done;
printf "\\n"
echo "$stats" > "$cache"
```
The output should look something like this
```
▆█▅▂█▃▁█
```
But I can only get the first output.

**Comment by ashish-yadav11** [comment]
One thing you can do is to gather all strings you have to output in a variable like -
```
s="foo"
s="${s}bar"
...
printf "%s\n" "$s"
```
meanwhile I am taking a look at the problem.

**Comment by ashish-yadav11** [comment]
The bug is now fixed. See [this commit](https://github.com/ashish-yadav11/dwmblocks/commit/9329d0dfe6e71f421cbc06baf4ccf8e8e78bbe03).
