### ISSUE TITLE
Could you make your dwmblocks work on top barmodules patch?

### ISSUE THREAD

**Issue by romariorobby** [ashish-yadav11/dwmblocks#20]
Here the link for [Barmodules patch](https://github.com/bakkeby/patches/wiki/barmodules)

**Comment by ashish-yadav11** [comment]
It shouldn't be too hard to write a patch, but the barmodules patch is too intrusive and I don't use it so I don't have enough motivation to do that. If you want to do it, you can copy most of the stuff from the provided patches (with and without systray ones) except for the drawbar and buttonpress function. You will just need to modify those parts.

**Comment by ashish-yadav11** [comment]
or Maybe you can request the writer of Barmodules patch to write one for this.

**Comment by BBaoVanC** [comment]
Wait, I'm confused. Isn't barmodules included by default?
