### ISSUE TITLE
small unicode characters

### ISSUE THREAD

**Issue by sourav-majumdar-math** [ashish-yadav11/dwmblocks#23]
![dwmblocks_screenshot](https://user-images.githubusercontent.com/66737585/117536280-c45b8280-b017-11eb-9850-58f700bd3b3e.png)

The two unicode characters besides the calendar turn out very small. The rest of icons are font-awesome, they seem fine.

**Comment by ashish-yadav11** [comment]
Then change the icon for those blocks. What's the issue?

**Comment by sourav-majumdar-math** [comment]
That is certainly possible. I was hoping if you would know a workaround for this? This is one of the icon`printf '|%b ' \\U1f5e0` I am trying to print. This turns out bigger in stdout than here.

**Comment by ashish-yadav11** [comment]
To increase the size of the 2 icons, firstly you will have to find out what font is displaying the icon. Then you can change that font's size in fonts array in config.h of dwm. For example I have `"Siji:pixelsize=12"` as one of the entries. This issue has nothing to do with dwmblocks. Personally I would recommend using icons from the same font.
