### ISSUE TITLE
Length of each block

### ISSUE THREAD

**Issue by sourav-majumdar-math** [ashish-yadav11/dwmblocks#24]
I am having some difficulty in getting to format the output of each block. I am executing a printf command that is perfectly indented when I output it onto a terminal and each output is of a fixed length.

```
printf "|  ↓ %6s%4s ↑ %6s%4s %4s%%" "$wifi_r_speed" "$u_r" "$wifi_t_speed" "$u_t" "$wifi_perc"
```
However on the statusbar the length of the block varies depending on the number of characters in each variable. Why is that?

I was guessing it may be due to the STATUSLENGTH variable, so I tried increasing the CMDOUTLENGTH variable but there was no effect.

In `dwmblocks.c` you have,
```
#define STATUSLENGTH                    (LENGTH(blocks) * (CMDOUTLENGTH + DELIMITERLENGTH) + 1)
```
but I noticed in my `dwm.c` there is a line `#define STATUSLENGTH            256`. Are these two STATUSLENGTH variables different?

**Comment by ashish-yadav11** [comment]
Is your font in the status bar monospace? I don't think the issue has anything to do with `CMDOUTLENGTH` or `STATUSLENGTH`. They can only cause truncation of output.

**Comment by ashish-yadav11** [comment]
Test by setting the status manually by say `xsetroot $(printf "|  ↓ %6s%4s ↑ %6s%4s %4s%%" "$wifi_r_speed" "$u_r" "$wifi_t_speed" "$u_t" "$wifi_perc")` at different times and see if the issue persists.

**Comment by sourav-majumdar-math** [comment]
Thank you very much for your reply. I was able to solve the issue by removing other fonts and homogenizing it only for monospace.
