### ISSUE TITLE
Time

### ISSUE THREAD

**Issue by santilococo** [ashish-yadav11/dwmblocks#25]
Hello! I have a question. Do you know why the time module gets out of sync? This occurs even after setting 60s of interval and calibrating dwmblocks to restart at 00s of a minute (the first time).

**Comment by ashish-yadav11** [comment]
The blocks don't update exactly after 60s. dwmblocks sleeps for 60s but updating the blocks also takes some time. I think that is causing the issue. I don't think this behaviour is a bug or can be fixed. If you can't tolerate one minute delay in the clock, I think you will have to lower the interval (maybe to 1s) (1s is what I use by the way).

**Comment by santilococo** [comment]
OK. Ty!
