### ISSUE TITLE
Increasing delimiterendchar affects clickability/pathc execution

### ISSUE THREAD

**Issue by jacktheritter** [ashish-yadav11/dwmblocks#26]
When using dwmblocks with the default _delimiterendchar_ of 10, every feature (including the clickability) works just fine. But after increasing the _delimiterendchar symbolic constant_ to anything above 10 (in **config.h** as well as in **dwm.c**), clickability stops working even though all related features such as cursor hinting and manual signaling persist functioning.
Does this happen due to recent updates or do you have to change anything else within dwm's or dwmblock's sourcecode?

**Comment by ashish-yadav11** [comment]
Are you using dwmblocks with systray?

**Comment by ashish-yadav11** [comment]
Without systray, I tested with DELIMITERENDCHAR set to 15 and it works for me.

**Comment by ashish-yadav11** [comment]
It works with systray as well. Have you updated your color codes? Start dwmblocks from the terminal and see if you get any error messages.

**Comment by ashish-yadav11** [comment]
Are you using the latest patch?

**Comment by ashish-yadav11** [comment]
Are you using the latest patch?

**Comment by ashish-yadav11** [comment]
Are you using the latest patch?

**Comment by jacktheritter** [comment]
I re-applied the latest (non-systray) patch, but apparently an old color sequence declaration was responsible for the behavior. Thanks for your support!
