### ISSUE TITLE
barpadding patch causes clickability misalignement

### ISSUE THREAD

**Issue by TimDev9492** [ashish-yadav11/dwmblocks#27]
After applying [this](https://dwm.suckless.org/patches/barpadding/dwm-barpadding-20200720-bb2e722.diff) barpadding patch to dwm, dwmblocks doesn't seem to be aware of the fact that the statusbar got shifted to the left. This affects the clickability of the dwmblocks modules and for them to recognize a mouse click, I have to click slightly to the right of a module. I don't know how to take the shift of the bar into account inside the code that's responsible for calculating the signal value and changing the cursor.

**Comment by ashish-yadav11** [comment]
Ofcourse it won't be. Do the following changes.

In `buttonpress`
```
                else if ((x = selmon->ww - RSPAD - ev->x) > 0 && (x -= wstext - LSPAD - RSPAD) <= 0) {
                        updatedwmblockssig(x);
                        click = ClkStatusText;
                } else
```
to
```
                else if ((x = selmon->ww - sp - RSPAD - ev->x) > 0 && (x -= wstext - LSPAD - RSPAD) <= 0) {
                        updatedwmblockssig(x);
                        click = ClkStatusText;
                } else
```

Similiarly in `motionnotify`
```
        } else if (ev->window == selmon->barwin && (x = selmon->ww - RSPAD - ev->x) > 0
                                                && (x -= wstext - LSPAD - RSPAD) <= 0)
                updatedwmblockssig(x);
```
to
```
        } else if (ev->window == selmon->barwin && (x = selmon->ww - sp - RSPAD - ev->x) > 0
                                                && (x -= wstext - LSPAD - RSPAD) <= 0)
                updatedwmblockssig(x);
```

**Comment by TimDev9492** [comment]
With these changes, everything works perfectly, thank you very much!

**Comment by Thegajout** [comment]
For anyone coming across this,
In `buttonpress`, this change should also be made:

From:
```
else if (ev->x < selmon->ww - wstext)
```
To:
```
else if (ev->x < selmon->ww - wstext - sp)
```
without this change, the right side of the blocks will not be clickable for the distance of `sp`, although the "hand" cursor will still be shown.

Also depending on which patch you have, `sp` might have to be changed to `2 * sp` in all the changes mentioned above.
