### ISSUE TITLE
Emojis

### ISSUE THREAD

**Issue by slococo** [ashish-yadav11/dwmblocks#28]
Hi, do you know why "double value Unicode" emojis are not displaying correctly? For example, ✈️ airplane; `2708 FE0F`. It will only show a part: [imgur](https://i.imgur.com/1LyMktc.png). I am using noto color emoji.
TY.

**Comment by ashish-yadav11** [comment]
I have no idea. Does adding a space after the emoji in the text not solve the issue?

**Comment by slococo** [comment]
I think this solves it. It seems like a good workaround... TY!
