### ISSUE TITLE
build errors

### ISSUE THREAD

**Issue by plasmoduck** [ashish-yadav11/dwmblocks#30]
Hi, I'm trying to build on FreeBSD and get these errors:

gcc -o dwmblocks -Wno-missing-field-initializers -Wno-unused-parameter -O3 -Wall -Wextra
dwmblocks.c
dwmblocks.c: In function 'writepid':
dwmblocks.c:274:24: error: 'S_IRUSR' undeclared (first use in this function)
  274 |                        S_IRUSR | S_IWUSR | S_IRGRP | S_IROTH)) == -1) {
      |                        ^~~~~~~
dwmblocks.c:274:24: note: each undeclared identifier is reported only once for each function it appears in
dwmblocks.c:274:34: error: 'S_IWUSR' undeclared (first use in this function)
  274 |                        S_IRUSR | S_IWUSR | S_IRGRP | S_IROTH)) == -1) {
      |                                  ^~~~~~~
dwmblocks.c:274:44: error: 'S_IRGRP' undeclared (first use in this function)
  274 |                        S_IRUSR | S_IWUSR | S_IRGRP | S_IROTH)) == -1) {
      |                                            ^~~~~~~
dwmblocks.c:274:54: error: 'S_IROTH' undeclared (first use in this function)
  274 |                        S_IRUSR | S_IWUSR | S_IRGRP | S_IROTH)) == -1) {
      |                                                      ^~~~~~~
*** Error code 1

**Comment by ashish-yadav11** [comment]
I am afraid there are many linux specific things in the source code at the moment.

**Comment by ashish-yadav11** [comment]
I may try to get rid of those but it won't happen anytime soon.

**Comment by plasmoduck** [comment]
There are a lot of forks I've found that build fine on BSD. I'd just rather use the original. It's good to more software portable.


On Fri, Oct 01, 2021 at 11:39:49PM -0700, Ashish Kumar Yadav wrote:
> I am afraid there are many linux specific things in the source code at the moment.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ashish-yadav11/dwmblocks/issues/30#issuecomment-932694296

-- 
Kind regards,

Chris Garvin
