### ISSUE TITLE
Migrate to systray (question)

### ISSUE THREAD

**Issue by slococo** [ashish-yadav11/dwmblocks#31]
Hi! I want to know if there is an easy way to migrate to the systray patch (I am using the vanilla dwmblocks patch at the moment, but I want to try sistray). Or do I need to revert the patch and then apply the systray one? TY.

**Comment by ashish-yadav11** [comment]
I think reverting and applying back the systray one after applying the systray patch would be easier.

**Comment by slococo** [comment]
TY!
