### ISSUE TITLE
xsetroot doesn't appear anymore when made changes to config.h on dwm-6.3

### ISSUE THREAD

**Issue by pigeon46** [ashish-yadav11/dwmblocks#32]

**Comment by ashish-yadav11** [comment]
Can you elaborate a little please?

**Comment by pigeon46** [comment]
I made changes to config.def.h, and pasted it onto config.h, upon rebooting, the default xsetroot, i.e my dwm version appears instead of dwmblocks. It actually works fine when I only just edited config.h, so I'm not sure if this is an issue anymore. I made this post before realizing that, so apologies for making an issue before testing it out properly. Thanks for this software btw! It's really straightforward and I'm having a blast using it.

**Comment by ashish-yadav11** [comment]
Closing this then. Happy that you found it helpful.
