### ISSUE TITLE
dwmblocks 6.3 patch doesn't work

### ISSUE THREAD

**Issue by CallMeRush** [ashish-yadav11/dwmblocks#35]
I have downloaded dwm version 6.3, and i have been trying to apply the dwmblocks patch for this version with no success. Looking at the diff file it seems like there are also all the differences between dwm version 6.2 and 6.3 (which I already have, since I have dwm 6.3), but i cannot understand which differences are the ones that are actually needed for dwmblocks to function, nor if some are missing (comparing this diff file with the 6.2 diff file I found different changes). Could you please help me?

**Comment by ashish-yadav11** [comment]
I have added a patch for v6.3, apply that.
