### ISSUE TITLE
updateblock - child - execv: No such file or directory

### ISSUE THREAD

**Issue by CallMeRush** [ashish-yadav11/dwmblocks#36]
I have been trying to start dwmblocks with a simple block saved on the blocks folder, but when I execute it this error comes up: "updateblock - child - execv: No such file or directory". What is the problem?
Also, is there a way to start dwmblocks without having to use sudo?

**Comment by ashish-yadav11** [comment]
You shouldn't need sudo first of all. Secondly the error is that dwmblocks is not able to locate the script path. Are you sure you have specified them correctly?

**Comment by CallMeRush** [comment]
I have been trying to use the whole path of the file, starting with "~/...", just the path to the file and using the PATH("script.sh") with no success. Do I need to specify somehow what PATH is?

**Comment by ashish-yadav11** [comment]
Show you config.h.
You must specify the whole path.

**Comment by ashish-yadav11** [comment]
You can use the macro defined at the top of the file.

**Comment by CallMeRush** [comment]
/* macro for conveniently specifying pathu and pathc below */
#define PATH(name)                      "<path to the folder containing block scripts>/"name

Which value should i change here? Sorry, I'm quite new to linux.

**Comment by CallMeRush** [comment]
static Block blocks[] = {
/*      pathu                           pathc                           interval        signal */
        { PATH("prova.sh"),             NULL,                           5,              0},
        { PATH("calendar.sh"),          NULL,                           30,             1},
        /*{ PATH("volume.sh"),            PATH("volume_button.sh"),       0,              2},
        { PATH("cpu_temp.sh"),          PATH("cpu_temp_button.sh"),     1,              4},
        { PATH("battery.sh"),           PATH("battery_button.sh"),      30,             3},*/
        { NULL }
};

the only thing I added is the "prova.sh", a script with only "printf "hello"" in it. But also calendar gives me the same issue.

**Comment by ashish-yadav11** [comment]
you should replace "/" by the full path of the folder you are using to store your script files.

**Comment by ashish-yadav11** [comment]
for exameple
`#define PATH(name)                      "/home/foo/.programs/dwmblocks/blocks/"name`

**Comment by CallMeRush** [comment]
I first had a "permission denied" error, and when i fixed it it went back to saying "no such file or directory"; but if I got the first error in the first place then it must have known where to find the file, right?

**Comment by CallMeRush** [comment]
Fixed it! Thank you for your time. 
(Also, it works without sudo, as it should).
