### ISSUE TITLE
When applying patch to a fresh dwm install, it says patch already applied.

### ISSUE THREAD

**Issue by pigeon46** [ashish-yadav11/dwmblocks#37]
When I try to patch the dwm-dwmblocks-6.3.diff, I get this

`patch < dwm-dwmblocks-6.3.diff
patching file config.def.h
Reversed (or previously applied) patch detected!  Assume -R? [n]`

**Comment by ashish-yadav11** [comment]
Wait, I messed up something, will fix in a while.

**Comment by ashish-yadav11** [comment]
Fixed, try now.
