### ISSUE TITLE
writepid - open: Permission denied

### ISSUE THREAD

**Issue by CallMeRush** [ashish-yadav11/dwmblocks#38]
I've been using dwmblocks flawlessly up to this evening, when it suddently stopped working. Whenever I try to start it, it says "writepid - open: Permission denied". 
I first had it starting on startup, but got rid of that option to check if that was the problem. I then even commented out all of the blocks in the config file, but still didnt't work. 
What's causing the problem? I've trying looking online but found nothing...

**Comment by ashish-yadav11** [comment]
Reinstall the program (just run `sudo make install` in the directory of the program), I think this would fix the issue. `dwmblocks` writes its pidfile in `/var/local/dwmblocks/`. Its permission somehow might have got changed on your system.

**Comment by brittibaroni** [comment]
I’ve tried to reinstall, with no success…

**Comment by brittibaroni** [comment]
Could it be some issue with the sound? Its not working anymore

**Comment by CallMeRush** [comment]
No, actually the audio is working... :/

**Comment by CallMeRush** [comment]
And dwmblocks is back running, no idea why. So frustrating.
