### ISSUE TITLE
Question about systray

### ISSUE THREAD

**Issue by pigeon46** [ashish-yadav11/dwmblocks#39]
Do I apply the systray patch on the suckless website _then_ apply the one in this repo, or does the one in this repo alone does the job?

**Comment by ashish-yadav11** [comment]
The README clearly mentions what you need to do. Please read that.

[patches](patches) folder contains two patches for dwm, ONE FOR DWM ALREADY
PATCHED WITH SYSTRAY PATCH and the other for vanilla dwm. One of the patches,
whichever appropriate, is essential for dwmblocks to function properly. It will
add support for colored text, clickability and cursor hinting when hovering on
clickable blocks (inspired by polybar).

**Comment by pigeon46** [comment]
Ok, thanks. Sorry for asking question without doing properly reasing first.

**Comment by pigeon46** [comment]
Ok I applied it and it worked perfeclty. Another question though, is there any way to have the systray to the _left_ of dwmblocks? I see that the diff removed that option from config.def.h, so there is a reason probably.

**Comment by ashish-yadav11** [comment]
I didn't have much time to look into it, so I did the simplest thing possible. I will look into integrating it later some time (I thought it wasn't that useful).

**Comment by pigeon46** [comment]
Ah, ok, understandable.
