### ISSUE TITLE
dwmblocks crashes: segmentation fault (core dumped)  dwmblocks

### ISSUE THREAD

**Issue by juacq97** [ashish-yadav11/dwmblocks#4]
I want to add a module for spotify, here is the script:

```
#! /bin/sh
icon="󰓇" 
status=$(~/.local/bin/status-bar/spotify_status.py)
runstate=$(pgrep -c spotify)

if [[ $runstate -le 1 ]]; then 
    echo ""
else
   # echo "$ifg $icon $tfg $status"
    echo "$icon $status"
fi
      
```
The `spotify-status.py` script I call is [this script](https://github.com/Jvanrhijn/polybar-spotify), but if I run dwmblocks I get an error `[1]    5988 segmentation fault (core dumped)  dwmblocks` (the 5988 change every time).

**Comment by ashish-yadav11** [comment]
It would be of great help if you could provide a sample output of the script when dwmblocks crashes. Also does the crash only happen when having this block? At what point does the crash happen?

**Comment by juacq97** [comment]
There's no output, the dwm bar remains as `dwm-6.2` and the terminal stays without output for like 2 seconds, then gave me the error message and exits. I tried with other modules (I copied and pasted other module I have) and there's no problem at all.

The detailed steps are:
- Add the module to dwmblocks: `{ PATH("spotify-bar"), NULL, 5, 9},`
- Run `make install`
- Run `dwmblocks`

**Comment by ashish-yadav11** [comment]
No, I was talking about the output from your spotify script.

**Comment by ashish-yadav11** [comment]
Running it independently of dwmblocks.

**Comment by juacq97** [comment]
It outputs the name of the song and an icon if the song is playing or paused:

```
$ ./spotify-bar
󰓇 ▶ Circus Maximus: The 1st Chapter
```

**Comment by ashish-yadav11** [comment]
Try increasing CMDLENGTH and/or STTLENGTH in dwmblocks.c

**Comment by juacq97** [comment]
That's it! Now it works as expected. Thanks!!
