### ISSUE TITLE
status2d patch

### ISSUE THREAD

**Issue by slococo** [ashish-yadav11/dwmblocks#40]
Hi! Do you know how can I apply this [patch](https://dwm.suckless.org/patches/status2d)?
Specifically in the `drawbar` function because dwmblocks modifies it.
Thanks.

**Comment by ashish-yadav11** [comment]
You are better off using torrinfail's dwmblocks if you want to use status2d for colors and stuff.

**Comment by wael444** [comment]
https://dwm.suckless.org/patches/statuscmd/dwm-statuscmd-status2d-20210405-60bb3df.diff....
