### ISSUE TITLE
How to use cursor hinting?

### ISSUE THREAD

**Issue by yogeshdcool** [ashish-yadav11/dwmblocks#41]
Can someone please add the instructions to use cursor hinting ?It would be very useful for beginners like me (I want to know too)

**Comment by ashish-yadav11** [comment]
you just need to apply the provided patch to dwm.

**Comment by yogeshdcool** [comment]
> you just need to apply the provided patch to dwm.

I should have stated the question more properly 
What I'm asking is how to use cursor hinting after patching it

**Comment by ashish-yadav11** [comment]
Its not something to put to use. If you hover the cursor on a clickable block, the shape of the cursor will change to a hand (hence cursor hinting), like in clickable links in web browsers.

**Comment by yogeshdcool** [comment]
> Its not something to put to use. If you hover the cursor on a clickable block, the shape of the cursor will change to a hand (hence cursor hinting), like in clickable links in web browsers.

I thought it was something else I should have first seached what cursor hinting is
