### ISSUE TITLE
How do I modify the drawbar function that will apply the statuspadding patch?

### ISSUE THREAD

**Issue by Hyoihz** [ashish-yadav11/dwmblocks#42]
This is the mentioned patch: [statuspadding](https://dwm.suckless.org/patches/statuspadding/dwm-statuspadding-6.3.diff)

So far I only have the [dwm-systray-dwmblocks-6.3](https://github.com/ashish-yadav11/dwmblocks/blob/master/patches/dwm-systray-dwmblocks-6.3.diff) applied. 

I would appreciate any type of help... 

Thank you!

**Comment by ashish-yadav11** [comment]
What happens when you don't touch the drawbar function, just apply the changes to the setup function from the patch?
