### ISSUE TITLE
`sigdmwblocks` doesn't seem to do anything when invoked from cron

### ISSUE THREAD

**Issue by Dook97** [ashish-yadav11/dwmblocks#46]
As the title says, calling `sigdwmblocks` from a cron job doesn't seem to have any effect. Using `kill SIGRTMIN+signal $(pgrep dwmblocks)` works just fine though.

**Comment by ashish-yadav11** [comment]
Why would you call sigdwmblocks from a cronjob, when dwmblocks itself has periodic updates? Anyway, it might be due to some user related issue. I will see if I can do something.

**Comment by Dook97** [comment]
> Why would you call sigdwmblocks from a cronjob, when dwmblocks itself has
> periodic updates?

Because I want to execute `sigdwmblocks` right after calling another program.

**Comment by Dook97** [comment]
Welp, turns out I'm just retarded and didn't realize that cron's `PATH` differs
from user's, which is why it didn't find the `sigdwmblocks` executable.

Sorry to have bothered you. Closing.

**Comment by ashish-yadav11** [comment]
No problem.
