### ISSUE TITLE
Increasing length of delimiter

### ISSUE THREAD

**Issue by paniash** [ashish-yadav11/dwmblocks#6]
Hello Ashish,
I'm using the upstream dwmblocks build by torrinfail. However, it only features the delimiter to be a single ASCII character (C char datatype). I'd be glad if you could help me point out how I could increase this delimiter size.

**Comment by ashish-yadav11** [comment]
The ability to have multiple characters as delimiter is already there in torrinfail's dwmblocks (it was added back recently).

**Comment by paniash** [comment]
Thanks a lot! I didn't know that.
