### ISSUE TITLE
Clickability is not working

### ISSUE THREAD

**Issue by mastopgunaf** [ashish-yadav11/dwmblocks#9]
I specified a file that should be ran when I click a block in blocks.h, however when I click that block, dwmblocks doesn't run the script at all. I'm trying to make a clickable volume block. Signalling works fine. I also applied a patch (without systray) from the patches folder to a clean dwm build and it still didn't work. These are the blocks in my blocks.h file:
```
static Block blocks[] = {
        { PATH("volume.sh"), PATH("volume_click.sh"), 0, 1 },
        { PATH("date.sh"), NULL, 1, 0 },
        { NULL } /* just to mark the end of the array */
};
```

This is my volume_click.sh:
```
#!/bin/sh

case "$1" in
        1) st pulsemixer &;;
        3) amixer sset Master 0%; sigdwmblocks 1;;
esac
```

Another detail: when I hover my mouse over the block that's clickable, my cursor changes accordingly, so maybe it partially recognizes it?

**Comment by ashish-yadav11** [comment]
Try adding `echo "$1" >~/dwmblocks.debug` to volume_click.sh to confirm whether the script is run at all on clicking.

**Comment by mastopgunaf** [comment]
> Try adding `echo "$1" >~/dwmblocks.debug` to volume_click.sh to confirm whether the script is run at all on clicking.
No, it doesn't do anything, the file is not created. I also checked earlier if it's running at all by making it spawn a terminal in a click scripts, it also didn't work.

**Comment by ashish-yadav11** [comment]
Probably, I have messed up the dwm patch. Will report you when fixed.

**Comment by mastopgunaf** [comment]
Thanks

**Comment by ashish-yadav11** [comment]
The bug is fixed now. You only have to change a couple of lines in buttonpress function in dwm. Change x from unsigned int to int.
